import {
  FaHome,
  FaUsers,
  FaUserFriends,
  FaBriefcase,
  FaEnvelope,
  FaBuilding,
  FaCalculator,
  FaFileInvoiceDollar,
  FaChartLine,
  FaBlog,
  FaInfoCircle,
  FaHandshake,
  FaBars,
  FaChevronDown,
  FaChevronUp,
  FaTimes,
  FaWhatsapp,
  FaFacebookF,
  FaInstagram,
  FaLinkedinIn,
} from "react-icons/fa";

export const iconesMap: Record<string, React.ComponentType<{ className?: string }>> = {
  "fa-solid fa-house": FaHome,
  "fa-solid fa-users": FaUsers,
  "fa-solid fa-user-group": FaUserFriends,
  "fa-solid fa-briefcase": FaBriefcase,
  "fa-solid fa-envelope": FaEnvelope,
  "fa-solid fa-building": FaBuilding,
  "fa-solid fa-calculator": FaCalculator,
  "fa-solid fa-file-invoice-dollar": FaFileInvoiceDollar,
  "fa-solid fa-chart-line": FaChartLine,
  "fa-solid fa-blog": FaBlog,
  "fa-solid fa-circle-info": FaInfoCircle,
  "fa-solid fa-handshake": FaHandshake,

  "fa-solid fa-bars": FaBars,
  "fa-solid fa-chevron-down": FaChevronDown,
  "fa-solid fa-chevron-up": FaChevronUp,
  "fa-solid fa-xmark": FaTimes,

  "bi bi-whatsapp": FaWhatsapp,
  "fa-brands fa-facebook-f": FaFacebookF,
  "fa-brands fa-instagram": FaInstagram,
  "fa-brands fa-linkedin-in": FaLinkedinIn,
};